name: Deploy Frontend

on:
  push:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t dermarkr/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true dermarkr/react-test npm test

      - name: Generate Deployment Package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: einaregilsson/beanstalk-deploy@v18
        with:
          application_name: frontend
          environment_name: Frontend-env
          version_label: ${{ github.sha }}
          region: ca-central-1
          deployment_package: deploy.zip
          existing_bucket_name: elasticbeanstalk-ca-central-1-514131334290
          bucket_path: frontend
          use_existing_bucket: true